defaults:
  - model: default
  - dataset@train_dataset: custom_train
  - dataset@val_dataset: custom_val
  - dataset@test_dataset: custom_test  # 新增测试集配置
  - loss: default

# Global variables
num_samples: 10000

# For 24GB GPU
train_dataloader:
  batch_size: 1
  num_workers: 4
  shuffle: True
  drop_last: True

val_freq: 5
val_dataloader:
  batch_size: 16
  num_workers: 16
  shuffle: False
  drop_last: False

# 新增测试参数
test_dataloader:
  batch_size: 16
  num_workers: 16
  shuffle: False
  drop_last: False
test_ckpt_path: "./logs/large_default/checkpoints"

lr: 3e-4
weight_decay: 0.1
max_grad_value: 1.0
gradient_accumulation_steps: 1
save_freq: 5

scheduler:
  _target_: pc_sam.optim.WarmupMultiStepLR
  milestones: [400000, 500000]
  warmup_iters: 3000
  warmup_factor: 0.001
  gamma: 0.1

pretrained_ckpt_path: ""
max_epochs: 100
max_steps: 5000000

# Logging
run_name: large_default
project_dir: "./logs/${run_name}"
log_with: None
log_dir: "./logs/${run_name}/metrics"
